/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabmalopes;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author rh4nyel
 */
public class Menu extends javax.swing.JFrame {
    
     
    public Menu() {
        initComponents();
        populateComboBoxColor();
        populateComboBoxTransform();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldX = new javax.swing.JTextField();
        jTextFieldZoom = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextFieldAngulo = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextFieldDy = new javax.swing.JTextField();
        jTextFieldGeometria = new javax.swing.JTextField();
        jTextFieldY = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTransform = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxCor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButtonCria = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldX.setText("-10 -10 15 -10 15 -10");
        jTextFieldX.setName("textFieldX"); // NOI18N
        jTextFieldX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXActionPerformed(evt);
            }
        });

        jTextFieldZoom.setName("textBoxZoom"); // NOI18N

        jTextField4.setName("textBoxDxCenter"); // NOI18N

        jTextFieldAngulo.setName("textFieldDx"); // NOI18N

        jTextField6.setName("textBoxDyCenter"); // NOI18N

        jTextFieldDy.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldDy.setName("textFieldDy"); // NOI18N

        jTextFieldGeometria.setName("textFieldGeometria"); // NOI18N

        jTextFieldY.setText("-10 0 0 -10 0 0");
        jTextFieldY.setName("textFieldY"); // NOI18N

        jTextFieldId.setName("textFieldId"); // NOI18N

        jLabel1.setText("X[]");

        jLabel2.setText("Y[]");

        jLabel3.setText("ID");

        jLabel4.setText("Geometria:");

        jLabel5.setText("Dx/Angulo");

        jLabel6.setText("Dy");

        jLabel7.setText("Zoom");

        jLabel8.setText("DxCenter");

        jLabel9.setText("DyCenter");

        jComboBoxTransform.setName("comboBoxTransform"); // NOI18N

        jLabel10.setText("Transform");

        jComboBoxCor.setName("comboBoxCor"); // NOI18N

        jLabel11.setText("Cor");

        jButtonCria.setText("Criar Geometria");
        jButtonCria.setName("buttonCria"); // NOI18N
        jButtonCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriaActionPerformed(evt);
            }
        });

        jButton2.setText("Aplicar Transformaçao");
        jButton2.setName("buttonTransform"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Aplicar Deslocamento e Zoom");
        jButton3.setName("buttonDeslocamento"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCria, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextFieldId)
                    .addComponent(jTextFieldY)
                    .addComponent(jTextFieldX)
                    .addComponent(jComboBoxCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTransform, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDy)
                    .addComponent(jTextFieldGeometria)
                    .addComponent(jTextFieldAngulo)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField4)
                        .addComponent(jTextFieldZoom)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addComponent(jButton3))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldZoom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldGeometria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxTransform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCria)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jComboBoxCor.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     Color color = new Color(1);
    private void jButtonCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriaActionPerformed
        
        System.out.println(this.jComboBoxCor.getSelectedIndex());
        switch(this.jComboBoxCor.getSelectedIndex())
        {
            case 0:
                color = Color.BLUE;
                
                    break;
            case 1:
                color = Color.RED;
                    break;
            case 2:
                color = Color.WHITE;
                    break;
            case 3:
                color = Color.GREEN;
                    break;
        }
        try {
            painel.setColor(color);
            CriaGeometria();
            repaint();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erro ao criar geometria");
        }
    }//GEN-LAST:event_jButtonCriaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Geometria geometria = null;
        int sizeG = painel.getGeometrias().size();
        int comboBoxTransformValue = this.jComboBoxTransform.getSelectedIndex();
        
         for(int i = 0; i<sizeG; i++)
                       {
                         String comp1 = painel.getGeometrias().get(i).getId();
                         String comp2 = this.jTextFieldGeometria.getText();

                           if(comp1.equals(comp2))
                           {

                               geometria = painel.getGeometrias().get(i);
                               
                           }
                       }
         painel.setDx(Float.parseFloat(this.jTextFieldAngulo.getText()));
         
         if(this.jTextFieldDy.getText() != "")
         painel.setDy(Float.parseFloat(this.jTextFieldDy.getText()));
         
         else
             painel.setDy(1f);

    
        
       switch(comboBoxTransformValue)
       {
           case 0: //rot
                        painel.aplicaRotacao(geometria);
               break;
           case 1: //transl
                 
                        painel.aplicaTranslacao(geometria);
               break;
           case 2: //escala
                        painel.aplicaEscala(geometria);
               break;
       }
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldXActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Geometria geometria = null;
        int sizeG = painel.getGeometrias().size();
        painel.setDx(Float.parseFloat(this.jTextFieldZoom.getText()));
        painel.setDy(Float.parseFloat(this.jTextFieldZoom.getText()));
        
         for(int i = 0; i<sizeG; i++)
                       {
                         String comp1 = painel.getGeometrias().get(i).getId();
                         String comp2 = this.jTextFieldGeometria.getText();

                           if(comp1.equals(comp2))
                           {

                               geometria = painel.getGeometrias().get(i);
                               
                           }
                       }
         
         painel.aplicaZoom(geometria);
    }//GEN-LAST:event_jButton3ActionPerformed

    
   private void populateComboBoxColor()
{
    String[] arrayColor;
    
    arrayColor = new String[4];
    arrayColor[0] = "BLUE";
    arrayColor[1] = "RED";
    arrayColor[2] = "WHITE";
    arrayColor[3] = "GREEN";
    
    this.jComboBoxCor.addItem(arrayColor[0]);
    this.jComboBoxCor.addItem(arrayColor[1]);
    this.jComboBoxCor.addItem(arrayColor[2]);
    this.jComboBoxCor.addItem(arrayColor[3]);
    

    // ...
}
   
   
  private void populateComboBoxTransform(){
      
      this.jComboBoxTransform.addItem("ROTACAO");
            this.jComboBoxTransform.addItem("TRANSLACAO");

                  this.jComboBoxTransform.addItem("ESCALA");

     
  }
    
    
    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
           /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
            
        });
        
        
    }
    JFrame principal = new JFrame(); 
    Painel painel = new Painel();
    String fieldX = "null";
    String fieldY = "null";
    String fieldId = "null";
    public void CriaGeometria() throws IOException
    {
        System.out.println("criando");
       principal.getContentPane().add(painel);
        principal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        principal.setSize(1000, 600);
        principal.setVisible(true);
       

            fieldX = this.jTextFieldX.getText();
            fieldY = this.jTextFieldY.getText();
        
       /*
        else
        {
            fieldX = fieldX + " " + this.jTextFieldX.getText();
            fieldY = fieldY + " " + this.jTextFieldY.getText();
            
        }*/
        fieldId = this.jTextFieldId.getText();
         System.out.println(fieldX);
        System.out.println(fieldY);
        // float[] testX = new float[]{10f, 20f, 20f, 0f};
       // float[] testY = new float[]{10f, 20f, 20f, 0f};
       String arrayStringX[], arrayStringY[];
       arrayStringX= fieldX.split(" ");
       arrayStringY= fieldY.split(" ");
       float[] fX = new float[arrayStringX.length];
       float[] fY = new float[arrayStringY.length];

       
       for(int i=0; i<arrayStringX.length; i++)
       {
           fX[i] = Float.parseFloat(arrayStringX[i]);

       }
       
         for(int i=0; i<arrayStringY.length; i++)
       {
            fY[i] = Float.parseFloat(arrayStringY[i]);
       }
       
       Geometria geometria = Geometria.build(fX, fY, fieldId);
        painel.addGeometria(geometria);
        principal.setVisible(true);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCria;
    private javax.swing.JComboBox<String> jComboBoxCor;
    private javax.swing.JComboBox<String> jComboBoxTransform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldAngulo;
    private javax.swing.JTextField jTextFieldDy;
    private javax.swing.JTextField jTextFieldGeometria;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    private javax.swing.JTextField jTextFieldZoom;
    // End of variables declaration//GEN-END:variables

 
}
